logging:
    level:
        root: warn
        liquibase: warn
        org.hibernate.sql: trace
        org.hibernate.type.descriptor.sql.BasicBinder: warn
        org.hibernate.orm.cache: trace

server:
    port: 8081
    servlet:
        context-path: /

rivulet:
    app:
        terminal-key:
            random-base: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
            length: 32
            timeout: 60
            time-unit: minutes
        git:
            repo-url: https://gitee.com/jqhsdtz/rivulet-functions.git
            local-dir: D:/WORKSPACE/laputa/rivulet-functions
            username: username
            password: password

spring:
    profiles:
        include: key
    redis:
        redisson:
            file: classpath:redisson.yml
    liquibase:
        enabled: false # 禁止springboot自动调用liquibase
    jpa:
        show-sql: true
        open-in-view: true
        hibernate:
            ddl-auto: none
        properties:
            javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                new_generator_mappings: false
                format_sql: false
                generate_statistics: true
                javax.cache:
                    missing_cache_strategy: create
                    provider: org.ehcache.jsr107.EhcacheCachingProvider
                    uri: classpath:ehcache.xml
                cache:
                    use_second_level_cache: true
                    use_query_cache: true
#                    org.hibernate.cache.jcache.internal.JCacheRegionFactory是JCacheRegionFactory最新的位置，在github搜这个路径
#                    可以避免搜到过时的代码
                    region.factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
    datasource:
        # 因为MySQL和MariaDB无法部分更新Column属性，会导致更新一个属性，丢失另一个属性，所以不用
        # 详见 https://github.com/liquibase/liquibase/pull/3045
        url: jdbc:postgresql://localhost:5432/postgres
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 90MB
