logging:
    level:
        root: info
server:
    port: 8081
    servlet:
        context-path: /
rivulet:
    app:
        init-key:
            random-base: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
            length: 32
            timeout: 30
            time-unit: minutes
spring:
    profiles:
        include: key
    redis:
        redisson:
          file: classpath:redisson.yml
    liquibase:
        enabled: false # 禁止springboot自动调用liquibase
        database-change-log-table: rv_db_change_log
        database-change-log-lock-table: rv_db_change_log_lock
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect # 使用MySQL8Dialect自动创建的表为InnoDB引擎
                new_generator_mappings: false
                format_sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/exapmle
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            #initial-size: 5 # 连接池初始化大小
            #min-idle: 10 # 最小空闲连接数
            #max-active: 20 # 最大连接数
            filters: stat,wall,slf4j
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: username
                login-password: password
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 90MB
