logging:
    level:
        root: info

server:
    port: 8081
    servlet:
        context-path: /

rivulet:
    app:
        terminal-key:
            random-base: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
            length: 32
            timeout: 30
            time-unit: minutes
        git:
            repo-url: https://gitee.com/jqhsdtz/rivulet-functions.git
            local-dir: D:/WORKSPACE/laputa/rivulet-functions
            username: username
            password: password

spring:
    profiles:
        include: key
    redis:
        redisson:
            file: classpath:redisson.yml
    liquibase:
        enabled: false # 禁止springboot自动调用liquibase
    jpa:
        show-sql: false
        open-in-view: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.laputa.rivulet.common.database.dialect.PostgreSQL14Dialect
                new_generator_mappings: false
                format_sql: true
    datasource:
        # 因为MySQL和MariaDB无法部分更新Column属性，会导致更新一个属性，丢失另一个属性，所以不用
        # 详见 https://github.com/liquibase/liquibase/pull/3045
        url: jdbc:postgresql://localhost:5432/postgres
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
        druid:
            #initial-size: 5 # 连接池初始化大小
            #min-idle: 10 # 最小空闲连接数
            #max-active: 20 # 最大连接数
            filters: stat,wall,slf4j
            web-stat-filter:
                enabled: true
                url-pattern: /*
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                reset-enable: false
                login-username: username
                login-password: password
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 90MB
